web/api/urls.py
from django.urls import path
from .views import TimeStepData

app_name = 'api'
urlpatterns = [
    # used to send data to use for AJAX calls, then make graphs with Chart.js
    path('<int:pk>/chart/data/', TimeStepData.as_view(), name="data"),
]

web/simulator/urls.py
from django.urls import path
from .views import (
    ExperimentCreate,
    ExperimentDetail,
    ExperimentList,
    show_landing,
    show_about_page,
)

app_name = 'simulator'
urlpatterns = [
    path('', show_landing, name="home"),
    path('experiments/', ExperimentList.as_view(), name="list"),
    path('add-experiment/', ExperimentCreate.as_view(),
         name='simulation_creator'),
    path('about/', show_about_page, name='about'),
    path('<int:pk>/', ExperimentDetail.as_view(), name='simulation_detail'),
]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('simulator.urls')),
    path('api/', include('api.urls'))
]

web/simulator/models.py
from django.db import models
from analysis.person import Person
from analysis.simulation import WebSimulation
from analysis.virus import Virus
from web import settings
from django.utils import timezone
from django.urls import reverse


class Experiment(models.Model):
    '''An experiment by the user to test the herd immunity of a population.'''
    title = models.CharField(max_length=settings.EXPER_TITLE_MAX_LENGTH,
                             unique=False,
                             help_text="Title of your experiment.")
    population_size = models.IntegerField(help_text=(
        "How large is the population?"))
    vaccination_percent = models.FloatField(help_text=(
        "What percentage of the population is initially vaccinated " +
        "against the virus?"
    ))
    virus_name = models.CharField(max_length=settings.EXPER_TITLE_MAX_LENGTH,
                                  unique=False, null=True,
                                  help_text="What virus are you testing?")
    mortality_chance = models.FloatField(help_text=(
        "How likely is a patient infected with the virus likely to succumb?" +
        " Must be a percentage between 0.00 and 1.00."
    ))
    reproductive_rate = models.FloatField(help_text=(
        "How effective is the virus at spreading between individuals?" +
        " Must be a percentage between 0.00 and 1.00."
    ))
    initial_infected = models.IntegerField(help_text=(
        "At the beginning of the experiment, how many people in the " +
        "population are infected with the virus?"
    ))

    def __str__(self):
        '''Return the title of the Experiment instance.'''
        return self.title

    def get_absolute_url(self):
        '''Returns a path to the experimental results after form submission.'''
        path_components = {'pk': self.pk}
        return reverse('simulator:simulation_detail', kwargs=path_components)

    def generate_web_sim(self):
        """Update atttributes for Simulation, based on new data from an
           Experiment instance.

           Parameters:
           self(Experiment): the calling Experiment instance

           Returns:
           WebSimulation: a new instance of the class

        """
        # init population related fields
        pop_size = self.population_size
        # init related fields, virus fields
        virus = Virus(self.virus_name, self.reproductive_rate,
                      self.mortality_chance)
        initial_infected = self.initial_infected
        vacc_percentage = self.vaccination_percent
        # create the population
        return WebSimulation(pop_size, vacc_percentage, virus,
                             initial_infected)

    def run_experiment(self):
        '''Runs through the experiment, and generates time step graphs.'''
        # update Simulation properties with form data
        web_sim = self.generate_web_sim()
        # run through the simulation, collect data to make TimeStep instances
        time_step_collection = web_sim.run_and_collect(self)
        # insert new TimeSteps into the db
        for ts in time_step_collection:
            time_step = TimeStep.objects.create(
                step_id=ts.get('step_id'),
                total_infected=ts.get('total_infected'),
                current_infected=ts.get('current_infected'),
                dead=ts.get('dead'),
                total_vaccinated=ts.get('total_vaccinated'),
                alive=ts.get('alive'),
                uninfected=ts.get('uninfected'),
                uninteracted=ts.get('uninteracted'),
                experiment=ts.get('experiment')
            )
            time_step.save()


class TimeStep(models.Model):
    '''A visual representation of a time step for a Simulation.'''
    step_id = models.IntegerField(help_text=(
        "What time step is this TimeStep for?"))
    experiment = models.ForeignKey(Experiment, on_delete=models.CASCADE,
                                   help_text="The related Experiment model.")
    total_infected = models.IntegerField(help_text=(
        "People who contracted the virus thus far in the experiment."
    ))
    current_infected = models.IntegerField(help_text=(
        "People infected who are still alive in this step of the experiment."
    ))
    dead = models.IntegerField(help_text="People thus far who have succumbed.")
    total_vaccinated = models.IntegerField(help_text=(
        "Amount of individuals who are now vaccinated in the population."
    ))
    alive = models.IntegerField(help_text="People who are currently alive.")
    uninfected = models.IntegerField(help_text=(
        "People who have not had any interaction with the virus."
    ))
    uninteracted = models.IntegerField(help_text=(
        "Alive people in the"
        + " population who are both uninfected, not vaccinated."))
    created = models.DateTimeField(auto_now_add=True,
                                   help_text=("The date and time this TimeStep"
                                              + " was created. Auto-generated "
                                              + "when the model " +
                                              "saves, used for ordering."))

    def __str__(self):
        '''Return a unique phrase identifying the TimeStep.'''
        return f'{self.experiment} Step {self.step_id}'

web/simulator/forms.py
from .models import Experiment, TimeStep
from django import forms


class ExperimentForm(forms.ModelForm):
    '''A form based off the  Experiment model.'''
    class Meta:
        model = Experiment
        exclude = [
            'init_report',
            'final_summary',
        ]

web/simulator/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView, CreateView, ModelFormMixin
from simulator.models import Experiment, TimeStep
from simulator.forms import ExperimentForm
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect


class ExperimentCreate(CreateView):
    '''User is able to make a new experiment on the system.'''
    model = Experiment
    form_class = ExperimentForm
    template_name = 'simulator/create.html'

    def form_valid(self, form, *args, **kwargs):
        '''Adds model instances to the db as appropriate.'''
        self.object = form.save()
        self.object.run_experiment()
        return HttpResponseRedirect(self.get_success_url())


class ExperimentDetail(DetailView):
    '''Displays a page with results of a specific experiment.'''
    model = Experiment
    template_name = 'simulator/results.html'

    def get(self, request, pk):
        """Renders a page to show the boarding instructions for a single Trip.

           Parameters:
           request(HttpRequest): the GET request sent to the server
           pk(int): unique id value of an Experiment instance

           Returns:
           HttpResponse: the view of the detail template

        """
        experiment = self.get_queryset().get(pk=pk)
        time_steps = TimeStep.objects.filter(experiment=experiment)
        context = {
            'experiment': experiment,
            'time_steps': time_steps
        }
        return render(request, self.template_name, context)


class ExperimentList(ListView):
    '''List all the Experiments that have been conducted by users.'''
    model = Experiment
    template_name = 'simulator/list.html'

    def get(self, request):
        """Get a list of all Experiment instances. """
        experiments = self.get_queryset().all()
        return render(request, self.template_name, {
          'experiments': experiments
        })


def show_landing(request):
    '''Render the landing page of the website.'''
    return render(request, 'simulator/index.html')


def show_about_page(request):
    '''Render the About page of the site, so users can get more info.'''
    return render(request, 'simulator/info.html')

web/simulator/templates/simulator/base.html
<!-- simulator/templates/simulator/base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Herd Immunity Simulation</title>

    <!-- Links to Bootstrap and CSS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>

    <!-- navbar -->
    {% load static %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">

    <div class="navbar-brand d-flex w-50 ml-2">
        <span class="text-white">
            <div class="row">
                <img src="{% static 'images/vaccine.png' %}" alt="logo" width="40px" heigth="40px">
                <h2><a href="{% url 'simulator:home' %}" style="color: white;">Herd Immunity</a></h2>
            </div>
        </span>
     </div>

        <!-- smaller button for smaller viewports -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon text-white"></span>
        </button>
        <!-- nav links -->
        <div class="collapse navbar-collapse" id="navbarContent">
             <ul class="list-group list-group-horizontal justify-content-end ml-auto" style="list-style-type: none;">
                <div class="row ml-auto mr-2">
                    <li>
                        <a href="{% url 'simulator:simulation_creator' %}" class="btn btn-primary ml-12">Experiment</a>
                    </li>
                    <li>
                        <a href="{% url 'simulator:list' %}" class="btn btn-secondary ml-2">See Results</a>
                    </li>
                    <li>
                        <a href="{% url 'simulator:about' %}" class="btn btn-info ml-2">About</a>
                    </li>
                </div>
            </ul>
        </div>
    </nav>

    <!-- content -->
        {% block content %}
        {% endblock %}

    <!-- jQuery and Ajax needed for Chart.js -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js'></script>
</body>
</html>

web/simulator/templates/simulator/create.html
<!-- simulator/templates/simulator/create.html -->
{% extends "simulator/base.html" %}

<!-- user sees a form for inputting disease data -->
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10">
            <!-- display form -->
            <h1>Herd Immunity Simulation</h1>

            <h3>Please fill out the form below.</h3>
            <p>
                <i>Is our population ready for the outbreak?</i> <br>
                Please look at <a href="https://www.theguardian.com/news/datablog/ng-interactive/2014/oct/15/visualised-how-ebola-compares-to-other-infectious-diseases">
                    this Guardian article</a> if you need examples of viruses to use in this simulation (includes mortality and reproductive rates). 
            </p>
            <!-- form for experimental values -->
            <form class="form-group" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary" value="See it Play Out!">
            </form>
            <br>
        </div>
    </div>
</div>

{% endblock %}

web/simulator/templates/simulator/index.html
<!-- simulator/templates/simulator/index.html -->

{% extends "simulator/base.html" %}
{% load static %}
{% block content %}
    <div class="jumbotron jumbotron-fluid bg-white text-white mb-0" style="background-image: url('{% static 'images/virus.jpg' %}'); background-position:center; height: 1000px;">
        <h1 class="display-1 text-center">Doubtful About Vaccines?</h1>
        <h2 class="text-center">See how they protect against epidemics.</h2>
        <hr class="my-4">
        <h3 class="text-center">Herd Immunity Simulator</h3>
        <br><br>
        <div class="row justify-content-center">
            <div class="offset-md-2 col-md-5">
                <!-- Link to ExperimentCreate -->
                <a class="btn btn-primary btn-lg" href="{% url 'simulator:simulation_creator'%}" role="button">Run your own experiment</a>
            </div>
            <div class="col-md-5">
                <!-- Link to ExperimentList -->
                <a class="btn btn-primary btn-lg" href="{% url 'simulator:list' %}" role="button">Look at Previous Results</a>
            </div>
            <br><br><br><br><br>
            <!-- Photo Credit -->
            <p class="text-center text-white">Background photo by CDC on Unsplash <br>
            Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a>
            </p>
        </div>
{% endblock %}

web/simulator/templates/simulator/info.html
<!-- simulator/templates/simulator/info.html -->
{% extends "simulator/base.html" %}

{% block content %}
    <div class="container">
        <h1>About Herd Immunity</h1>
        <h3>Rules</h3>
        <h5>Please read below to better understand how the simulation works.</h5>
        <ol>
            <li>
                A sick person only has a chance at infecting healthy, unvaccinated people they encounter.
            </li>
            <li>
                An infected person cannot infect a vaccinated person.
            </li>
            <li>
                At the end of a time step, an infected person will either die of the infection or get better.  The chance they will die is the percentage chance represented by the virus mortality rate.
            </li>
            <li>
                For the sake of simplicity, if the person does not die, we will consider them immune to the virus.
            </li>
            <li>
                Dead people can no longer be infected, either. People who die no longer count as infected.
            </li>
            <li>
                All state changes for a person should occur at the **end** of a time step, after all infected persons have finished all of their interactions.
            </li>
            <li>
                The state of an individual who starts out at the beginning of a time step as infected, is resolved by determining if they survive or succumb to the illness.
            </li>
        </ol>
        <p>(Written based off the ReadMe instructions produced by Alan Davis and Jess Dahmen, on <a href="https://github.com/Make-School-Courses/CS-1.1-Intro-to-Programming/tree/master/Projects/herdimmunity_starter_term2_2019">the Herd Immunity starter code GitHub repository</a>).</p>
        <h3>What is Herd Immunity, and Why Should I Care?</h3>
        <h5>Check out the resources below to learn more!</h5>
        <ol>
            <li>
                <!-- display a cool informational videos and links -->
                <p>Vox video featuring Bill Gates, 2015:</p>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/9AEMKudv5p0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </li>
            <li>
                <p>
                    <a href="https://www.theatlantic.com/science/archive/2018/04/what-bill-gates-fears-most/559007/">
                        Ed Yong and Bill Gates Explain Microbes, 2018
                    </a>
                </p>
            </li>
            <li>
                <p>Video Explanation of Herd Immunity by the Oxford VaccineGroup, 2018</p>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/8BUCi5Tuzms" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </li>
            <li>
                <p>
                    <a href="https://www.theguardian.com/news/datablog/ng-interactive/2014/oct/15/visualised-how-ebola-compares-to-other-infectious-diseases">
                        Article on Infectious Diseases by David McCandless, 2014
                    </a>
                </p>
            </li>
        </ol>
    </div>

{% endblock %}

web/simulator/templates/simulator/list.html
<!-- simulator/templates/simulator/list.html -->
{% extends "simulator/base.html" %}

{% block content %}
<div class="container">
    <!-- display title of page, and number of simulations to display -->
    <h1>Past Simulations <small class="text-muted">({{ experiments|length }})</small></h1>
    <p>Thank you for your curiosity! <br>
        The following is a list of all experiments that others have ran on this site so far. <br>
        Please use this site as a tool to do your own research, and to make your own conclusions about public health.
    </p>

    <ul>
        {% for experiment in experiments %}
            <li>
                <h3>{{ experiment.title }}</h3>
                {% include 'partials/experiment-info.html' %}
                <div class="row ml-auto">
                    <div class="offset-md-7">
                        <a class="btn btn-info" href="{% url 'simulator:simulation_detail' experiment.id %}">See In-Depth</a>
                    </div>
                </div>
                <br>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

web/simulator/templates/simulator/results.html
<!-- simulator/templates/simulator/results.html -->
{% extends "simulator/base.html" %}

<!-- user sees results of the simulation -->
{% block content %}
<div class="container">
    <h1>And the Results Are In!</h1>
    <h2>Did your population survive the epidemic?</h2>
    <hr
    <!-- display initial settings of simulation -->
    <h3>Initial Conditions</h3>
    {% include 'partials/experiment-info.html' %}
    <!-- display time steps -->
    <hr>
    <h3>Progression</h3>
    <p>What happened at each stage of the epidemic?</p>
    <!-- Table of Time Steps -->
    {% if time_steps %}
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Step #</th>
                <th scope="col">Total Infected</th>
                <th scope="col">Current Infected</th>
                <th scope="col">Dead</th>
                <th scope="col">Total Vaccinated</th>
                <th scope="col">Total Alive</th>
                <th scope="col">Unifected individuals</th>
                <th scope="col">Uninteracted individuals</th>
            </tr>
         </thead>
         <tbody>
            {% for time_step in time_steps %}
                <tr>
                    <th scope="row">{{ time_step.step_id }}</th>
                    <td>{{ time_step.total_infected }}</td>
                    <td>{{ time_step.current_infected }}</td>
                    <td>{{ time_step.dead }}</td>
                    <td>{{ time_step.total_vaccinated }}</td>
                    <td>{{ time_step.alive  }}</td>
                    <td>{{ time_step.uninfected }}</td>
                    <td>{{ time_step.uninteracted }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <hr>
    <h3>Final Results</h3>
    <p>Here is the breakdown of the population, at the end of the experiment:</p>
    <h5 class="text-center">Herd Immunity Resistance to {{ experiment.virus_name }} Outbreak</h5>
    <!-- Display of Bar Chart -->
        <canvas id="barChart" width="400" height="400"></canvas>
        {% include 'partials/pie-chart.html' %}
    {% else %}
    <!-- alert that there are no time steps in this experiment -->
    <div class="alert alert-info" role="alert">
        Your population is safe! The virus did not cause an epidemic.
    </div>
    {% endif %}
    <hr>
    <h3>Notes:</h3>
    <ol>
        <li>
            "Uninteracted": meaning individuals alive, not vaccinated, and not infected.
        </li>
        <li>
            "Total infected": although displayed in each time step, this value is<br>
             culmulative for the entire duration of the experiment.
        </li>
    </ol>
    <br>
    <!-- link to start another simulation -->
    <div class="offset-md-10">
        <a href="{% url 'simulator:list' %}" class="btn btn-primary">See More Simulations</a>
    </div>
    <br><br>
</div>

{% endblock %}